---

- name: Install Unbound packages
  tags: unbound
  apt:
    name: "{{ packages }}"
  vars:
   packages:
     - unbound

- name: Basic unbound config files
  tags: unbound
  set_fact:
    unboundConfig:
     - unbound.conf.d/access.conf
    unboundDNS64Config:
    - unbound.conf.d/dns64.conf

- name: Add DNS64 to unbound config list
  tags: unbound
  set_fact:
    unboundConfig: "{{ unboundConfig + unboundDNS64Config }}"
  when: dns64Enabled == True

- name: Deploy config for unbound
  tags: unbound
  template:
    src: "{{ item }}"
    dest: "/etc/unbound/{{ item }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: restart unbound
  with_items:
    - "{{ unboundConfig }}"

